FROM rust:1.92-slim AS builder
WORKDIR /usr/src/synapse
COPY . .
RUN cargo build --release -p synapse-server

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/synapse/target/release/synapse-server /usr/local/bin/synapse-server

RUN mkdir /tmp/sockets && chmod 777 /tmp/sockets
CMD ["synapse-server"]
